pipeline {

    agent any

    environment {

        IMAGE_TAG = "${BUILD_NUMBER}"

        IMAGE_NAME = "docker.io/aryansr/chatbot_frontend"
    }

    stages {

        stage('Checkout Repo') {

            steps {

                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/networknuts/devops-projects-2026.git'
            }
        }

        stage('Build and Push Docker Image') {

            steps {

                script {

                    dir('chatbot-app-docker/frontend/') {

                        def dockerImage = docker.build(
                            "${IMAGE_NAME}:${IMAGE_TAG}",
                            "."
                        )

                        docker.withRegistry('', 'dockerhub-credentials') {

                            dockerImage.push("${IMAGE_TAG}")
                        }
                    }
                }
            }
        }
    }
}
